Algoritmo "Par_ou_impar"
// Verificar se número é PAR ou IMPAR
Var
// Seção de Declarações das variáveis 
N1, par: INTEIRO


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("PAR OU IMPAR")
escreval (" ")
escreval ("Digite um número")
leia (n1)
par <- n1 mod 2
se (par = 0) ENTAO
escreval (" ")
   escreval ("par")
SENAO
escreval (" ")
ESCREVAL ("IMPAR")
fimse

Fimalgoritmo