Algoritmo "Par_ou_Impar"
// Programa para verificar se é par ou ímpar
Var
// Seção de Declarações das variáveis 
numero, divisao: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("            PAR OU IMPAR")
escreval (" ")
escreval ("Digite um número: ")
leia (numero)
divisao <- numero mod 2

se (divisao = 0) entao
escreval ("PAR")
senao
escreval ("IMPAR")
fimse


Fimalgoritmo